baseURL = "https://yaginumahidetatsu.com"
languageCode = "en-us"
title = "yaginumahidetatsu.com"
theme = "kiss"
copyright = "(c) <a href=\"https://github.com/ygnmhdtt\">Hidetatsu Yaginuma</a> 2018"
disqusShortname = "shortname"
Paginate = 4
enableRobotsTXT = true
publishDir = "docs"

[permalinks]
post = "/:year/:month/:day/:filename"

[params.info]
homeTitle = "ygnmhdtt" # Title for home page

[taxonomies]
tag ="tags"
